### ISSUE TITLE
Not buildable with recent ghc/library version

### ISSUE THREAD

**Issue by magthe** [pjones/playlists#7]
The latest version doesn't build with recent ghc/library versions. I looks like it isn't too difficult to make it build again though. I made a rough attempt at it [here](https://github.com/magthe/playlists/commit/5e130d237e04fd9da38f4b9f214737deade5d3a6). It builds and the tests pass, but I'm pretty sure that the version ranges in the Cabal file aren't fully correct now.

It would be nice to have a version that builds with ghc 9.8.

**Comment by pjones** [comment]
@magthe I will have some free time in a couple of weeks and then I will get this sorted out.

**Comment by magthe** [comment]
> @magthe I will have some free time in a couple of weeks and then I will get this sorted out.

Thanks, that would be wonderful. Please do let me know if there's anything I can do to assist you.

**Comment by pjones** [comment]
I updated the dependencies and list of compilers.  The latest version is now out on Hackage.

Thank you for bringing this to my attention.
